version: '3.8'

services:
  postgres-compose:
    container_name: db-growdiary
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Senhaum-2"
      POSTGRES_DB: growdiary
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  pgadmin-compose:
    container_name: pgadmin-growdiary
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "dsds.douglas@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "Senhaum-2"
    ports:
      - "15432:80"
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge