version: '3.8'

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Senhaum-2"
    ports:
      - "5432:5432"
#    volumes:
#      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "dsds.douglas@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "Senhaum-2"
    ports:
      - "15432:80"
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge

#version: '3.3'
#
#services:
#  postgres-db:
#    image: postgres:latest
#    ports:
#      - 5432:5432
#    environment:
#        POSTGRES_PASSWORD: postgres
#        POSTGRES_USER: postgres
#        PGDATA: /var/lib/postgresql/data
#    volumes:
#      - ./data/postgres:/var/lib/postgresql/data

#volumes:
#  data: {}

#  db:
#    image: postgres:9.4
#    ports:
#      - 5432:5432
#    environment:
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_USER: postgres
#      PGDATA: /var/lib/postgresql/data
#    volumes:
#      - /projects/own/docker_php/pgdata:/var/lib/postgresql/data