version: '3.3'

services:
  postgres-db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        PGDATA: /var/lib/postgresql/data
#    volumes:
#      - ./data/postgres:/var/lib/postgresql/data

#volumes:
#  data: {}

#  db:
#    image: postgres:9.4
#    ports:
#      - 5432:5432
#    environment:
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_USER: postgres
#      PGDATA: /var/lib/postgresql/data
#    volumes:
#      - /projects/own/docker_php/pgdata:/var/lib/postgresql/data